AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-eks-lambda-mfa

  Sample SAM Template for todo-eks-lambda-mfa

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  LambdaMFAFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda_mfa/
      Handler: app.lambda_handler
      Runtime: python3.9
      # Architectures:
      # - x86_64
      # Events:
      #   HelloWorld:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /lambda_mfa
      #       Method: get

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   LambdaMFAApi:
#     Description: API Gateway endpoint URL for Prod stage for Lambda MFA function
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lambda_mfa/"
#   LambdaMFAFunction:
#     Description: Hello World Lambda Function ARN
#     Value: !GetAtt LambdaMFAFunction.Arn
#   LambdaMFAFunctionIamRole:
#     Description: Implicit IAM Role created for LambdaMFA function
#     Value: !GetAtt LambdaMFAFunctionRole.Arn
